---
- name: apt-get update
  apt: update_cache=yes cache_valid_time=3600

- name: Install apt essentials
  apt:
    name: '{{ item }}'
    state: 'present'
  with_items: essentials_apt

- name: Install pip essentials
  pip:
    name: '{{ item }}'
    state: 'present'
  with_items: essentials_pip
